version: '3.9'
services:
  php: 
    image: php:7.4-apache
    ports:
      - 80:80
  db:
    build: 
      context: ./
    container_name: mysql8
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
        - ./core/database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306